software:
  biopath:
    repo: https://github.com/sebschmi/biopath
    version: 7422f3d6c484073c9d8926fd826c630ec1e5165d

  BubbleFinder:
    repo: https://github.com/sebschmi/BubbleFinder
    version: f2476ece35b8f8d565df3c4d2f9426f99367911e

  random-gfa-graph-generator:
    repo: https://github.com/sebschmi/random-gfa-graph-generator
    version: a561fdfaca7458bdddd7f1cb1ca74feadc7606d4