software:
  biopath:
    repo: https://github.com/sebschmi/biopath
    version: 8fdbcde0d75a851279fc3f5feb1fd93f9287a633

  BubbleFinder:
    repo: https://github.com/sebschmi/BubbleFinder
    version: 5a26837691fd01baaa6df62d1c5cb2dc746882a4

  random-gfa-graph-generator:
    repo: https://github.com/sebschmi/random-gfa-graph-generator
    version: a561fdfaca7458bdddd7f1cb1ca74feadc7606d4