software:
  biopath:
    repo: https://github.com/sebschmi/biopath
    version: 75069ea92aa07c1fb81b4c1a4bd3a619ade7b178

  BubbleFinder:
    repo: https://github.com/algbio/BubbleFinder
    version: 28ef1e35e1a0ba530ea36b2b31c0e1e5d1ee1c6d

  random-gfa-graph-generator:
    repo: https://github.com/sebschmi/random-gfa-graph-generator
    version: a561fdfaca7458bdddd7f1cb1ca74feadc7606d4